"""Turn one MiMo-V2.6-RL-oss row into one Harbor task directory.

Every value here comes from the explorer's runner (app/runner/domains.py), which mirrors Xiaomi's harness
(XiaomiMiMo/verl + mimoagent) and is the "original" side of the parity runs. Output is deterministic: the same
source revision, image lock and adapter version give byte-identical task directories.

Layout of a generated task:
    task.toml         [environment].docker_image pinned by digest; setup runs once from [environment.healthcheck]
    instruction.md    the prompt the explorer gives OpenCode, word for word
    environment/      Dockerfile (FROM the same digest) and setup/, the readable copy of what the healthcheck runs
    tests/            test.sh and everything grading needs; Harbor uploads it only after the agent finishes
"""

from __future__ import annotations

import base64
import io
import json
import shlex
import tarfile
from pathlib import Path

from app.runner import domains as ref
from app.runner.opencode import ANSWER_HOSTS
from app import catalog

from . import images, source

ADAPTER_VERSION = "1.1.0"
HERE = Path(__file__).parent
TPL = HERE / "templates"
VENDOR = HERE.parent / "app" / "vendor"
MUSIC_IMAGE = "docker.io/library/python@sha256:f77ac9e44ae96ef2c90b8053ea08c31f8be030f824196b0ae4db6d462c84e51f"  # 3.12-slim-trixie
ABCMIDI = "abcmidi=20250216+ds-1"   # what the explorer's python:3.12-slim (trixie) installs
MCP_PIN = "'mcp==1.26.0'"
TEXT_JUDGE = "thinkingmachines/Inkling"                              # app/models.py TEXT_JUDGES[0]
VISION_JUDGE = "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8"   # app/models.py VISION_JUDGES[0]
ROUTER = "https://router.huggingface.co/v1"

# The reference step limits (verl config/agent/*): Harbor tasks cannot carry a step limit, so they go in
# [metadata] and the per-domain job configs (jobs/*.yaml) pass them to the agent.
STEPS = {"code": ref.Code.steps, "cyber": ref.Cyber.steps, "general": ref.General.steps, "terminal": ref.Terminal.steps,
         "webdev": ref.Webdev.steps, "music": 4}
AGENT_TIMEOUT = {"code": ref.Code.timeout, "cyber": ref.Cyber.timeout, "general": ref.General.timeout,
                 "webdev": ref.Webdev.timeout, "music": 900}
RESOURCES = {"code": (2, 8192), "cyber": (2, 8192), "general": (2, 8192), "terminal": (1, 2048), "webdev": (2, 8192),
             "music": (1, 2048)}   # cpu-upgrade-class sandboxes, as the explorer uses; Terminal-Bench rows set their own


def slug(task_id: str) -> str:
    s = "".join(c if c.isalnum() or c in "-_." else "-" for c in task_id.lower())
    return s.strip("-.")


def fill(tpl: str, **values: str) -> str:
    text = (TPL / tpl).read_text()
    for k, v in values.items():
        text = text.replace(f"@@{k}@@", v)
    if "@@" in text:
        raise ValueError(f"{tpl}: unfilled placeholder")
    return text


PREAMBLE = """#!/bin/bash
# Runs once, as root, before the agent starts: Harbor's [environment.healthcheck] unpacks this folder into
# /var/lib/mimo and runs it. Generated by mimo_harbor; see its README for how each step maps to Xiaomi's harness.
M=/var/lib/mimo
[ -f "$M/ready" ] && exit 0
chmod 700 "$M"
fail() { echo "setup: $*" >&2; exit 1; }
# the answer-leak blocklist (mimoagent), applied to /etc/hosts by the agent right after it installs
write_blocklist() { cp "$M/files/blocklist" "$M/blocklist"; }
"""
POSTAMBLE = '\ntouch "$M/ready"\necho "setup done"\n'


def _residue_scrub() -> str:
    # base.py _RESIDUE_SCRUB_GLOBAL, except that /logs is Harbor's own (agent and verifier output): empty it of
    # image residue instead of deleting it.
    s = ref.RESIDUE_SCRUB.replace("rm -rf /tests /logs 2>/dev/null; ",
                                  "rm -rf /tests 2>/dev/null; find /logs -mindepth 1 -delete 2>/dev/null; "
                                  "mkdir -p /logs/agent /logs/verifier /logs/artifacts; chmod 777 /logs/agent /logs/verifier /logs/artifacts; ")
    assert s != ref.RESIDUE_SCRUB
    return s


def _tar_b64(files: dict[str, bytes]) -> str:
    """A reproducible .tar.gz (fixed mtimes, owners and order) as base64."""
    buf = io.BytesIO()
    import gzip
    with gzip.GzipFile(fileobj=buf, mode="wb", mtime=0) as gz, tarfile.open(fileobj=gz, mode="w", format=tarfile.USTAR_FORMAT) as t:
        for name in sorted(files):
            info = tarfile.TarInfo(name)
            info.size, info.mode, info.mtime, info.uid, info.gid = len(files[name]), 0o700, 0, 0, 0
            t.addfile(info, io.BytesIO(files[name]))
    return base64.b64encode(buf.getvalue()).decode()


def _toml_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)   # a JSON string is a valid TOML basic string


class Task:
    """Everything one Harbor task needs, before it is written to disk."""

    def __init__(self, task_id: str, row: dict):
        self.id, self.row, self.kind = task_id, row, source.kind(row)
        self.inst = row["instance"]
        self.files: dict[str, bytes] = {}          # path in the task dir -> bytes
        self.setup_files: dict[str, bytes] = {}    # what the healthcheck unpacks into /var/lib/mimo
        self.verifier_env: dict[str, str] = {}
        self.mcp: list[dict] = []
        self.agent_user: str | None = None
        self.meta: dict = {}
        getattr(self, f"_{self.kind}")()

    # ── per domain ────────────────────────────────────────────────────────
    def _code(self):
        cwd = self.inst["cwd"]
        self.image, self.workdir = images.pinned(f"{source.IMAGE_REPO}:{source.image_tag(self.row)}"), cwd
        self.instruction = ref.Code.prompt.format(task=self.row["prompt"])
        self.body = fill("code_setup.sh", CWD=shlex.quote(cwd), RESIDUE_SCRUB=_residue_scrub(),
                         CLEAN_EXCLUDES=" ".join(f"--exclude={d}" for d in ref.CLEAN_KEEP),
                         GLOBAL_CACHE_SCRUB=ref.GLOBAL_CACHE_SCRUB)
        self.blocklist = True
        rc = ref.reset_cmd(self.inst["test_patch"], "$BASE") or "true"
        vt = int(self.inst.get("verifier_timeout_sec") or 1800)
        self.files["tests/test.sh"] = fill("code_test.sh", CWD=shlex.quote(cwd), RESET_CMD=rc, TEST_TIMEOUT=str(vt)).encode()
        self.files["tests/test.patch"] = self.inst["test_patch"].encode()
        self.files["tests/test_command.sh"] = self.inst["test_command"].encode()
        self.verifier_timeout = vt + 300
        self.agent_timeout = AGENT_TIMEOUT["code"]

    def _cyber(self):
        exp = catalog.cyber_expected(self.inst.get("description") or self.row["prompt"])
        self.image, self.workdir = images.pinned(f"{source.IMAGE_REPO}:{source.image_tag(self.row)}"), "/home/agent"
        self.instruction = ref.Cyber.prompt.format(task=self.row["prompt"])
        self.setup_files["files/expected_func.json"] = json.dumps(exp).encode()
        self.setup_files["files/server_arvo.py"] = (VENDOR / "server_arvo.py").read_bytes()
        self.body = (TPL / "cyber_setup.sh").read_text()
        self.blocklist, self.agent_user = True, "agent"
        self.files["tests/test.sh"] = (TPL / "cyber_test.sh").read_bytes()
        self.files["tests/verify.py"] = (TPL / "cyber_verify.py").read_bytes()
        self.files["tests/server_arvo.py"] = (VENDOR / "server_arvo.py").read_bytes()
        self.verifier_timeout, self.agent_timeout = 300, AGENT_TIMEOUT["cyber"]
        self.meta["expected_crash"] = exp

    def _general(self):
        env = self.id
        man = json.loads(source.fetch(f"general/envs/{env}/manifest.json").read_text())
        cwd = man["cwd"]
        self.image, self.workdir = images.pinned(f"{source.IMAGE_REPO}:{source.image_tag(self.row)}"), cwd
        self.instruction = ref.General.prompt.format(cwd=cwd, task=source.fetch(f"general/envs/{env}/instruction.md").read_text())
        prefix = f"general/envs/{env}/"
        listing = {f["path"][len(prefix):]: f for f in source.general_files()[env]}
        fetch = []
        for up in man["uploads"]:   # the agent's workspace and the systems' code and data; not the verifier's files
            for rel, f in listing.items():
                if rel == up["source"] or rel.startswith(up["source"].rstrip("/") + "/"):
                    tail = rel[len(up["source"]):].lstrip("/")
                    fetch.append({**{k: v for k, v in f.items()}, "target": up["target"].rstrip("/") + ("/" + tail if tail else "")})
        fetch.sort(key=lambda f: f["target"])
        self.setup_files["files/fetch.json"] = json.dumps({"dataset": source.DATASET, "revision": source.REVISION,
                                                           "files": fetch}, indent=0, sort_keys=True).encode()
        self.setup_files["files/fetch.py"] = (TPL / "general_fetch.py").read_bytes()
        ports = " ".join(str(int(p)) for p in man.get("wait_ports") or [])
        self.body = fill("general_setup.sh", MCP_PIN=MCP_PIN, SETUP_CMD=shlex.quote(man["setup"]["command"]),
                         SETUP_TIMEOUT=str(int(man["setup"].get("timeout_sec") or 300)), PORTS=ports, CWD=shlex.quote(cwd))
        self.blocklist, self.agent_user = True, "agent"
        self.mcp = [{"name": s["name"], "transport": "streamable-http", "url": s["url"]} for s in man["mcp_servers"]]
        vt = int(man["verifier"].get("timeout_sec") or self.inst.get("verifier_timeout_sec") or 900)
        ver = man["verifier"]
        for up in ver["uploads"]:   # hidden until grading
            for rel in listing:
                if rel == up["source"] or rel.startswith(up["source"].rstrip("/") + "/"):
                    self.files[f"tests/verifier/{rel}"] = source.fetch(prefix + rel).read_bytes()
        self.files["tests/test.sh"] = (TPL / "general_test.sh").read_bytes()
        self.files["tests/grade.py"] = (TPL / "general_grade.py").read_bytes()
        self.files["tests/grade.json"] = json.dumps({
            "cwd": cwd, "wait_ports": [int(p) for p in man.get("wait_ports") or []], "uploads": ver["uploads"],
            "command": ver["command"], "timeout_sec": vt,
            "reward_file": ver.get("reward_file") or "/logs/verifier/reward.json",
            "reward_detail_file": ver.get("reward_detail_file") or "/logs/verifier/reward_detail.json"},
            indent=1, sort_keys=True).encode()
        self.verifier_env = {"GA_JUDGE_KEY": "${HF_TOKEN}", "GA_JUDGE_URL": "${MIMO_JUDGE_URL:-" + ROUTER + "}",
                             "GA_JUDGE_MODEL": "${MIMO_TEXT_JUDGE:-" + TEXT_JUDGE + "}", "GA_JUDGE_API": "chat",
                             "VERIFY_DETERMINISTIC": "1", "VERIFY_AGENT_JUDGE": "1"}
        self.verifier_timeout, self.agent_timeout = vt + 300, AGENT_TIMEOUT["general"]
        self.meta["systems"] = len(self.mcp)

    def _terminal(self):
        cwd = self.inst.get("cwd") or "/app"
        self.image, self.workdir = images.pinned(f"{source.IMAGE_REPO}:{source.image_tag(self.row)}"), cwd
        self.instruction = ref.General.prompt.format(cwd=cwd, task=self.inst["problem_statement"])
        self.body = fill("terminal_setup.sh", CWD=shlex.quote(cwd))
        self.blocklist = False
        for name, b64 in json.loads(self.inst["tests_files"]).items():
            self.files[f"tests/{'task_test.sh' if name == 'test.sh' else name}"] = base64.b64decode(b64)
        self.files["tests/test.sh"] = fill("terminal_test.sh", CWD=shlex.quote(cwd)).encode()
        self.verifier_timeout = float(self.inst.get("verifier_timeout_sec") or 300) + 120
        self.agent_timeout = float(self.inst.get("agent_timeout_sec") or 900)
        self.resources = (int(self.inst.get("cpus") or 1), int(self.inst.get("memory_mb") or 2048),
                          int(self.inst["storage_mb"]) if self.inst.get("storage_mb") else None)
        self.meta["original_allow_internet"] = self.inst.get("allow_internet")

    def _webdev(self):
        cwd = self.inst.get("cwd") or "/workspace"
        self.image, self.workdir = images.pinned(f"{source.IMAGE_REPO}:{source.image_tag(self.row)}"), cwd
        tmpl = (VENDOR / "webdev" / "agent_prompt.txt").read_text()
        self.instruction = tmpl.replace("{{cwd}}", cwd) + "\n\nBuild a website for the following request:\n\n" + self.row["prompt"]
        self.body = fill("webdev_setup.sh", CWD=shlex.quote(cwd))
        self.blocklist = False
        for f in ("__init__.py", "shot.py", "eval_rubric.py", "verdict.py"):   # a package: verdict.py imports .eval_rubric
            self.files[f"tests/webdev/{f}"] = (VENDOR / "webdev" / f).read_bytes()
        self.files["tests/test.sh"] = (TPL / "webdev_test.sh").read_bytes()
        self.files["tests/grade.py"] = (TPL / "webdev_grade.py").read_bytes()
        self.files["tests/grade.json"] = json.dumps({"cwd": cwd, "query": self.row["prompt"]}, indent=1, ensure_ascii=False).encode()
        self.verifier_env = {"WEBDEV_JUDGE_KEY": "${HF_TOKEN}", "WEBDEV_JUDGE_URL": "${MIMO_JUDGE_URL:-" + ROUTER + "}",
                             "WEBDEV_JUDGE_MODEL": "${MIMO_VISION_JUDGE:-" + VISION_JUDGE + "}"}
        self.verifier_timeout, self.agent_timeout = 1200, AGENT_TIMEOUT["webdev"]

    def _music(self):
        self.image, self.workdir = MUSIC_IMAGE, "/app"
        # The original is one completion with no tools; here the reply goes to a file, with the agent held to a few
        # steps and only a write tool (jobs/music.yaml), and the scorer reads that reply exactly as it read the text.
        self.instruction = (self.row["prompt"].rstrip() + "\n\n---\nWrite your complete reply to /app/answer.md.")
        self.body = "mkdir -p /app\n"
        self.blocklist = False
        pkg = VENDOR / "music_scorer"
        for p in sorted(pkg.rglob("*")):
            if p.is_file() and "__pycache__" not in p.parts:
                self.files[f"tests/music_scorer/{p.relative_to(pkg)}"] = p.read_bytes()
        self.files["tests/test.sh"] = fill("music_test.sh", ABCMIDI=ABCMIDI).encode()
        self.files["tests/grade.py"] = (TPL / "music_grade.py").read_bytes()
        self.verifier_timeout, self.agent_timeout = 600, AGENT_TIMEOUT["music"]
        self.meta["reference_response_length"] = 100000

    # ── shared ────────────────────────────────────────────────────────────
    def build(self) -> dict[str, bytes]:
        if self.blocklist:
            self.setup_files["files/blocklist"] = ("# mimo answer-leak blocklist (mimoagent)\n" +
                                                   "".join(f"0.0.0.0 {h}\n" for h in ANSWER_HOSTS)).encode()
        setup = PREAMBLE + "\n" + self.body.rstrip() + "\n" + POSTAMBLE
        self.setup_files["setup.sh"] = setup.encode()
        payload = _tar_b64(self.setup_files)
        hc = ("bash -c " + shlex.quote("test -f /var/lib/mimo/ready || { mkdir -p /var/lib/mimo && echo " + payload +
                                        " | base64 -d | tar -xzf - -C /var/lib/mimo && bash /var/lib/mimo/setup.sh; }"))
        out = dict(self.files)
        for name, data in self.setup_files.items():
            out[f"environment/setup/{name}"] = data
        out["environment/Dockerfile"] = (f"# The task's image, pinned by digest (the same as [environment].docker_image).\n"
                                         f"# Setup runs at start from [environment.healthcheck]; environment/setup/ is its readable copy.\n"
                                         f"FROM {self.image}\n").encode()
        out["instruction.md"] = self.instruction.encode()
        out["task.toml"] = self._toml(hc).encode()
        return out

    def _labels(self) -> tuple[str, str | None, str | None, list[str]]:
        """(title, category, difficulty, keywords) from the explorer's catalog index (web/data/index.json.gz), so
        Harbor tooling such as the Harbor Visualiser can show and filter tasks."""
        e = catalog.record(self.id) or {}
        f = e.get("f") or {}
        title = (e.get("t") or self.id).strip()
        cat_key = {"code": "prog", "cyber": "project", "general": "industry", "terminal": "industry",
                   "webdev": "site", "music": "family"}[self.kind]
        category = f.get(cat_key)
        category = category[0] if isinstance(category, list) else category
        tier = f.get("tier")
        difficulty = tier if tier and tier != "Unrated" else None
        words = [self.kind]
        for v in f.values():
            for x in (v if isinstance(v, list) else [v]):
                if isinstance(x, str) and x and x not in ("Unspecified", "None named", "Unrated") and x not in words:
                    words.append(x)
        words += [t for t in (self.inst.get("tags") or []) if t not in words]
        return title, category, difficulty, words

    def _toml(self, healthcheck: str) -> str:
        cpus, mem, *rest = getattr(self, "resources", RESOURCES[self.kind]) + (None,)
        storage = rest[0] if rest else None
        title, category, difficulty, words = self._labels()
        self.meta.update({"title": title, "keywords": words, **({"category": category} if category else {}),
                          **({"difficulty": difficulty} if difficulty else {})})
        m = {"source_dataset": source.DATASET, "source_revision": source.REVISION, "source_id": self.id,
             "domain": self.kind, "adapter": f"mimo_harbor {ADAPTER_VERSION}", "reference_step_limit": STEPS[self.kind],
             "reference_harness": "XiaomiMiMo/verl a2ad9f6 + XiaomiMiMo/mimoagent 467f0a1", **self.meta}
        L = ['schema_version = "1.4"', "",
             "[task]", f"name = {_toml_str('mimo-v2.6-rl/' + slug(self.id))}",
             f"description = {_toml_str(title[:300])}",
             f"keywords = {json.dumps(['mimo-v2.6-rl', self.kind])}", "",
             "[metadata]"]
        for k in sorted(m):
            v = m[k]
            L.append(f"{k} = {json.dumps(v, ensure_ascii=False, sort_keys=True) if not isinstance(v, dict) else _inline(v)}")
        L += ["", "[agent]", f"timeout_sec = {float(self.agent_timeout)}"]
        if self.agent_user:
            L.append(f'user = "{self.agent_user}"')
        L += ["", "[verifier]", f"timeout_sec = {float(self.verifier_timeout)}", 'user = "root"']
        if self.verifier_env:
            L += ["", "[verifier.env]"] + [f"{k} = {_toml_str(v)}" for k, v in sorted(self.verifier_env.items())]
        L += ["", "[environment]", f"docker_image = {_toml_str(self.image)}", f"workdir = {_toml_str(self.workdir)}",
              f"cpus = {cpus}", f"memory_mb = {mem}"] + ([f"storage_mb = {storage}"] if storage else []) + \
             ['network_mode = "public"', "build_timeout_sec = 1800.0"]
        L += ["", "[environment.healthcheck]", "# one-time setup before the agent (environment/setup/setup.sh)",
              f"command = {_toml_str(healthcheck)}", "timeout_sec = 1200.0", "retries = 0", "interval_sec = 5.0"]
        for s in self.mcp:
            L += ["", "[[environment.mcp_servers]]", f"name = {_toml_str(s['name'])}",
                  f"transport = {_toml_str(s['transport'])}", f"url = {_toml_str(s['url'])}"]
        return "\n".join(L) + "\n"


def _inline(d: dict) -> str:
    return "{ " + ", ".join(f"{k} = {json.dumps(v, ensure_ascii=False)}" for k, v in sorted(d.items())) + " }"


def write(task: Task, out_dir: Path) -> Path:
    files = task.build()
    d = out_dir / task.kind / slug(task.id)
    if d.exists():
        import shutil
        shutil.rmtree(d)
    for rel, data in sorted(files.items()):
        p = d / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)
        if rel.endswith(".sh"):
            p.chmod(0o755)
    return d
